### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by isaackogan** [isaackogan/OmeglePy#1]
- Implement full proxy support
- Implement anti-proxy-detection measures
- Clean up event handler
- Fix captcha answering

**Comment by Threadz112** [comment]
How do i install and get this working step by step if i may ask?

**Comment by isaackogan** [comment]
pip install OmeglePy

**Comment by Threadz112** [comment]
I get a error saying press any button to continue.

**Comment by Threadz112** [comment]
Traceback (most recent call last):
  File "C:\Users\Christian\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Christian\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Users\Christian\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\Christian\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 242, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "C:\Users\Christian\Desktop\OmeglePy-master\fa\fa\fa.py", line 354
    © 2021 GitHub, Inc.
    ^
SyntaxError: invalid character '©' (U+00A9)
Press any key to continue . . .

**Comment by isaackogan** [comment]
Not sure what that means. Open an issue with screenshots/error logs and I can try help.

Note for above:
- Proxy support added
- Anti-detection added
- Bot recoded in async (event handler too obviously)
- Captchas auto-kill the client unless overriden with a custom event handler
